# Generated by Django 3.2.15 on 2022-09-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../ApiProjectAssets/default_profile_wojr3s', upload_to='images/'),
        ),
    ]
